version: '3.8'
services:
  pdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
        - db:/var/lib/postgresql/data
  web:
    depends_on:
      - pdb
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db: